package: media_manager_responsive
version: '1.0.2'
author: 'Alexander Walther'
supportpage: https://www.alexplus.de

requires:
    redaxo: ^5.13
    mediapool: ^2.11
    media_manager: ^2.12
    yform: ^4

page:
    hidden: true
    
pages: 
    media_manager/media_manager_responsive:
        title: translate:media_manager_responsive_page
        perm: admin
        subpages:
            profile:
                title: translate:media_manager_responsive_page_profile
                perm: admin
            settings:
                title: translate:media_manager_responsive_page_settings
                perm: admin
            docs:
                title: translate:media_manager_responsive_page_docs
                subPath: README.md

default_config:
    cache_warmup: "enhanced"
