package: media_manager_responsive
version: '0.5.1-dev'
author: 'Alexander Walther'
supportpage: https://www.alexplus.de

requires:
    redaxo: ^5.13
    mediapool: ^2.11
    media_manager: ^2.12
    yform: ^4

page:
    hidden: true

pages: 
    media_manager/media_manager_responsive:
        title: translate:media_manager_responsive_page
        perm: admin
    media_manager/overview/responsive:
        title: translate:media_manager_responsive_page
        subPath: README.md
